apiVersion: v1
kind: Pod
metadata: 
  name: example-pod
  labels:
    purpose: demonstrate-args
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["echo"]
    args: ["Hello Kubernetes"]
