apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
spec:
  containers:
    - name: main-container
      image: nginx
      ports:
        - containerPort: 80
    - name: sidecar-container
      image: busybox
      command: ['sh', '-c', 'tail -f /var/log/nginx/access.log']
      volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-logs
  volumes:
    - name: nginx-logs
      emptyDir: {}
